//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Polomka.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id_Order { get; set; }
        public int Id_Service { get; set; }
        public int Id_Employee { get; set; }
        public int Id_Client { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Services Services { get; set; }
    }
}
